apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: zib34nfxb-python 
  janus-idp.io/tekton: zib34nfxb-python
  backstage.io/kubernetes-id: zib34nfxb-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zib34nfxb-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml